@Test @OtherAssetsMiniJourney @acceptance
Feature: Other Assets Mini journey(Adding  and removing other assets)

  Background: Common Steps - Transfer Details Journey
    Given I cleared the data for the service
    When I navigate to the "Auth Login Stub Page"
    And I enter redirect URL on Auth Login Stub Page for "Journey entry URL"
    When I enter Enrollment Key "HMRC-PODSPP-ORG", Identifier Name "PSPID" and Identifier Value "21000005" on "Auth Login Stub Page"
    And I click submit button on "Auth Login Stub Page"
    Then I am presented with the "Dashboard Page"
    And I click on "Start new transfer" hyperlink on "Dashboard Page"
    And I am presented with the "What You Will Need Page"
    And I navigated to the "Type Of Asset Page"
    Then I am presented with the "Type Of Asset Page"
    And I should see the heading "Type of assets included in the transfer"


  Scenario:1. PSA/PSP user is able to transfer a Other Assets
    And I "select" checkbox "Other" on "Type Of Asset Page"
    And I click save and continue button on "Type Of Asset Page"
    And I navigated to the "Add Other Assets Start Page"
    Then I am presented with the "Add Other Assets Start Page"
    And I should see the following values on the page
      | The following questions are about Other Assets that is part of this transfer. |
    And I click save and continue button on "Add Other Assets Start Page"
    Then I am presented with the "Other Assets Description Page"
    And I should see the heading "Describe the asset and how it was valued"
    When I enter the following data into corresponding input fields on "Other Assets Description Page"
      | value | Other Assets value description|
    And I click save and continue button on "Other Assets Description Page"
    Then I am presented with the "Other Assets Value Page"
    When I enter the following data into corresponding input fields on "Other Assets Value Page"
      | value | 500 |
    And I click save and continue button on "Other Assets Value Page"
    Then I am presented with the "Other Assets Check Your Answers Page"
    And I should see the heading "Check your answers"
    When I click on "change-other-assets-value" button on "Other Assets Check Your Answers Page"
    Then I am presented with the "Change Other Assets Value Page"
    When I enter the following data into corresponding input fields on "Change Other Assets Value Page"
      | value | 5000 |
    And I click save and continue button on "Change Other Assets Value Page"
    When I click on "change-other-assets-description" button on "Other Assets Check Your Answers Page"
    Then I am presented with the "Change Other Assets Description Page"
    When I enter the following data into corresponding input fields on "Change Other Assets Description Page"
      | value | Change Other Assets value description|
    And I click save and continue button on "Change Other Assets Description Page"
    And I click save and continue button on "Other Assets Check Your Answers Page"
    Then I am presented with the "Other Assets Amend Continue Page"
    And I should see the heading "You have added 1 asset"
    And I should see two radio buttons: "Yes" and "No"
    When I select radio button "No" on "Other Assets Amend Continue Page"
    And I click save and continue button on "Other Assets Amend Continue Page"
    Then I am presented with the "Check Your Answers Page"
    And I should see the heading "Check your answers"
    And I click save and continue button on "Check Your Answers Page"

  Scenario:2 . PSA/PSP user is able to transfer multiple other assets
    And I "select" checkbox "Other" on "Type Of Asset Page"
    And I click save and continue button on "Type Of Asset Page"
    And I navigated to the "Add Other Assets Start Page"
    Then I am presented with the "Add Other Assets Start Page"
    And I should see the following values on the page
      | The following questions are about Other Assets that is part of this transfer. |
    And I click save and continue button on "Add Other Assets Start Page"
    Then I am presented with the "Other Assets Description Page"
    And I should see the heading "Describe the asset and how it was valued"
    When I enter the following data into corresponding input fields on "Other Assets Description Page"
      | value | Other Assets value description|
    And I click save and continue button on "Other Assets Description Page"
    Then I am presented with the "Other Assets Value Page"
    When I enter the following data into corresponding input fields on "Other Assets Value Page"
      | value | 500 |
    And I click save and continue button on "Other Assets Value Page"
    Then I am presented with the "Other Assets Check Your Answers Page"
    And I should see the heading "Check your answers"
    And I click save and continue button on "Other Assets Check Your Answers Page"
    Then I am presented with the "Other Assets Amend Continue Page"
    And I should see the heading "You have added 1 asset"
    And I should see two radio buttons: "Yes" and "No"
    When I select radio button "No" on "Other Assets Amend Continue Page"
    And I click save and continue button on "Other Assets Amend Continue Page"
    Then I am presented with the "Check Your Answers Page"
    And I should see the heading "Check your answers"
    When I click on "change-other-assets-amend" button on "Check Your Answers Page"
    Then I am presented with the "Change Other Assets Amend Continue Page"
    And I should see two radio buttons: "Yes" and "No"
    When I select radio button "Yes" on "Change Other Assets Amend Continue Page"
    And I click save and continue button on "Change Other Assets Amend Continue Page"
    Then I am presented with the "Second Other Assets Description Page"
    #And I should see the heading "Describe the Other Assets and how it was valued"
    When I enter the following data into corresponding input fields on "Second Other Assets Description Page"
      | value | Other Assets value description|
    And I click save and continue button on "Second Other Assets Description Page"
    Then I am presented with the "Second Other Assets Value Page"
    When I enter the following data into corresponding input fields on "Second Other Assets Value Page"
      | value | 5000 |
    And I click save and continue button on "Second Other Assets Value Page"
    And I click save and continue button on "Second Other Assets Check Your Answers Page"
    Then I am presented with the "Other Assets Amend Continue Page"
    And I should see the heading "You have added 2 assets"
    And I should see two radio buttons: "Yes" and "No"
    When I select radio button "No" on "Other Assets Amend Continue Page"
    And I click save and continue button on "Other Assets Amend Continue Page"
    Then I am presented with the "Check Your Answers Page"
    And I should see the heading "Check your answers"
    And I click save and continue button on "Check Your Answers Page"

  Scenario:3 . PSA/PSP user is able to remove the other assets from the added list
    And I "select" checkbox "Other" on "Type Of Asset Page"
    And I click save and continue button on "Type Of Asset Page"
    And I navigated to the "Add Other Assets Start Page"
    Then I am presented with the "Add Other Assets Start Page"
    And I should see the following values on the page
      | The following questions are about Other Assets that is part of this transfer. |
    And I click save and continue button on "Add Other Assets Start Page"
    Then I am presented with the "Other Assets Description Page"
    And I should see the heading "Describe the asset and how it was valued"
    When I enter the following data into corresponding input fields on "Other Assets Description Page"
      | value | Other Assets value description|
    And I click save and continue button on "Other Assets Description Page"
    Then I am presented with the "Other Assets Value Page"
    When I enter the following data into corresponding input fields on "Other Assets Value Page"
      | value | 500 |
    And I click save and continue button on "Other Assets Value Page"
    Then I am presented with the "Other Assets Check Your Answers Page"
    And I should see the heading "Check your answers"
    And I click save and continue button on "Other Assets Check Your Answers Page"
    Then I am presented with the "Other Assets Amend Continue Page"
    And I should see the heading "You have added 1 asset"
    And I should see two radio buttons: "Yes" and "No"
    When I select radio button "No" on "Other Assets Amend Continue Page"
    And I click save and continue button on "Other Assets Amend Continue Page"
    Then I am presented with the "Check Your Answers Page"
    And I should see the heading "Check your answers"
    When I click on "change-other-assets-amend" button on "Check Your Answers Page"
    Then I am presented with the "Change Other Assets Amend Continue Page"
    And I should see two radio buttons: "Yes" and "No"
    When I select radio button "Yes" on "Change Other Assets Amend Continue Page"
    And I click save and continue button on "Change Other Assets Amend Continue Page"
    Then I am presented with the "Second Other Assets Description Page"
    #And I should see the heading "Describe the Other Assets and how it was valued"
    When I enter the following data into corresponding input fields on "Second Other Assets Description Page"
      | value | Other Assets value description|
    And I click save and continue button on "Second Other Assets Description Page"
    Then I am presented with the "Second Other Assets Value Page"
    When I enter the following data into corresponding input fields on "Second Other Assets Value Page"
      | value | 5000 |
    And I click save and continue button on "Second Other Assets Value Page"
    And I click save and continue button on "Second Other Assets Check Your Answers Page"
    Then I am presented with the "Other Assets Amend Continue Page"
    And I should see the heading "You have added 2 assets"
    When I click on "other-assets-confirm-removal" button on "Property Amend Continue Page"
    Then I am presented with the "Other Assets Confirm Removal Page"
    And I should see two radio buttons: "Yes" and "No"
    When I select radio button "Yes" on "Other Assets Confirm Removal Page"
    And I click save and continue button on "Other Assets Confirm Removal Page"
    Then I am presented with the "Other Assets Amend Continue Page"
    And I should see the heading "You have added 1 asset"
    When I select radio button "No" on "Other Assets Amend Continue Page"
    And I click save and continue button on "Other Assets Amend Continue Page"
    Then I am presented with the "Check Your Answers Page"
    And I click save and continue button on "Check Your Answers Page"