@Test @UnquotedSharesMiniJourney @acceptance
Feature: Unquoted Share Mini journey(Adding  and removing Unquoted Shares)

  Background: Common Steps - Transfer Details Journey
    Given I cleared the data for the service
    When I navigate to the "Auth Login Stub Page"
    And I enter redirect URL on Auth Login Stub Page for "What You Will Need Page"
    When I enter Enrollment Key "HMRC-PODSPP-ORG", Identifier Name "PSPID" and Identifier Value "2131231231231" on "Auth Login Stub Page"
    And I click submit button on "Auth Login Stub Page"
    And I am presented with the "What You Will Need Page"
    And I navigated to the "Type Of Asset Page"
    Then I am presented with the "Type Of Asset Page"
    And I should see the heading "Type of assets included in the transfer"

  Scenario:1. PSA/PSP user is able to transfer a Unquoted Shares
    And I "select" checkbox "Unquoted shares" on "Type Of Asset Page"
    And I click save and continue button on "Type Of Asset Page"
    Then I am presented with the "Add UnQuoted Share Start Page"
    And I should see the following values on the page
      | The following questions are about Unquoted shares that is part of this transfer. |
    And I click save and continue button on "Add UnQuoted Share Start Page"
    Then I am presented with the "Name Of Company Unquoted Share Page"
    And I should see the heading "What is the name of the company these unquoted shares relate to?"
    When I enter the following data into corresponding input fields on "Name Of Company Unquoted Share Page"
      | value | Company XYZ|
    And I click save and continue button on "Name Of Company Unquoted Share Page"
    Then I am presented with the "Value Of Unquoted Share Page"
    When I enter the following data into corresponding input fields on "Value Of Unquoted Share Page"
      | value | 500 |
    And I click save and continue button on "Value Of Unquoted Share Page"
    Then I am presented with the "Number Of Unquoted Share Page"
    And I should see the heading "How many unquoted shares in this company are part of this transfer?"
    When I enter the following data into corresponding input fields on "Number Of Unquoted Share Page"
      | value | 100 |
    And I click save and continue button on "Number Of Unquoted Share Page"
    Then I am presented with the "Class Of Unquoted Share Page"
    And I should see the heading "What class are these unquoted shares?"
    When I enter the following data into corresponding input fields on "Class Of Unquoted Share Page"
      | value | Class A|
    And I click save and continue button on "Class Of Unquoted Share Page"
    Then I am presented with the "Unquoted Share Check Your Answers Page"
    And I should see the heading "Check your answers"
    When I click on "change-unquoted-shares-company-name" button on "Unquoted Share Check Your Answers Page"
    Then I am presented with the "Change Name Of Company Unquoted Share Page"
    When I enter the following data into corresponding input fields on "Name Of Company Unquoted Share Page"
      | value | Company ABC|
    And I click save and continue button on "Change Name Of Company Unquoted Share Page"
    When I click on "change-unquoted-shares-value" button on "Unquoted Share Check Your Answers Page"
    Then I am presented with the "Change Value Of Unquoted Share Page"
    When I enter the following data into corresponding input fields on "Change Value Of Unquoted Share Page"
      | value | 5000 |
    And I click save and continue button on "Change Value Of Unquoted Share Page"
    When I click on "change-unquoted-shares-number" button on "Unquoted ShareCheck Your Answers Page"
    Then I am presented with the "Change Number Of Unquoted Share Page"
    When I enter the following data into corresponding input fields on "Change Number Of Unquoted Share Page"
      | value | 10 |
    And I click save and continue button on "Change Number Of Unquoted Share Page"
    When I click on "change-unquoted-shares-class" button on "Unquoted Share Check Your Answers Page"
    Then I am presented with the "Change Class Of Unquoted Share Page"
    When I enter the following data into corresponding input fields on "Change Class Of Unquoted Share Page"
      | value | Class B |
    And I click save and continue button on "Change Class Of Unquoted Share Page"
    Then I am presented with the "Unquoted Share Check Your Answers Page"
    And I click save and continue button on "Unquoted Share Check Your Answers Page"
    Then I am presented with the "Unquoted Share Amend Continue Page"
    And I should see the heading "You have added 1 group of unquoted shares"
    And I should see two radio buttons: "Yes" and "No"
    When I select radio button "No" on "Unquoted Share Amend Continue Page"
    And I click save and continue button on "Unquoted Share Amend Continue Page"
    Then I am presented with the "Check Your Answers Page"
    And I should see the heading "Check your answers"
    And I click save and continue button on "Check Your Answers Page"

  Scenario:2 . PSA/PSP user is able to transfer multiple Unquoted Shares
    And I "select" checkbox "Unquoted shares" on "Type Of Asset Page"
    And I click save and continue button on "Type Of Asset Page"
    Then I am presented with the "Add UnQuoted Share Start Page"
    And I should see the following values on the page
      | The following questions are about Unquoted shares that is part of this transfer. |
    And I click save and continue button on "Add UnQuoted Share Start Page"
    Then I am presented with the "Name Of Company Unquoted Share Page"
    And I should see the heading "What is the name of the company these unquoted shares relate to?"
    When I enter the following data into corresponding input fields on "Name Of Company Unquoted Share Page"
      | value | Company XYZ|
    And I click save and continue button on "Name Of Company Unquoted Share Page"
    Then I am presented with the "Value Of Unquoted Share Page"
    When I enter the following data into corresponding input fields on "Value Of Unquoted Share Page"
      | value | 500 |
    And I click save and continue button on "Value Of Unquoted Share Page"
    Then I am presented with the "Number Of Unquoted Share Page"
    And I should see the heading "How many unquoted shares in this company are part of this transfer?"
    When I enter the following data into corresponding input fields on "Number Of Unquoted Share Page"
      | value | 100 |
    And I click save and continue button on "Number Of Unquoted Share Page"
    Then I am presented with the "Class Of Unquoted Share Page"
    And I should see the heading "What class are these unquoted shares?"
    When I enter the following data into corresponding input fields on "Class Of Unquoted Share Page"
      | value | Class A|
    And I click save and continue button on "Class Of Unquoted Share Page"
    Then I am presented with the "Unquoted Share Check Your Answers Page"
    And I should see the heading "Check your answers"
    And I click save and continue button on "Unquoted Share Check Your Answers Page"
    Then I am presented with the "Unquoted Share Amend Continue Page"
    And I should see the heading "You have added 1 group of unquoted shares"
    When I select radio button "Yes" on "Unquoted Share Amend Continue Page"
    And I click save and continue button on "Unquoted Share Amend Continue Page"
    Then I am presented with the " Second Name Of Company Unquoted Share Page"
    And I should see the heading "What is the name of the company these unquoted shares relate to?"
    When I enter the following data into corresponding input fields on "Name Of Company Unquoted Share Page"
      | value | Company ABC|
    And I click save and continue button on "Second Name Of Company Unquoted Share Page"
    Then I am presented with the "Second Value Of Unquoted Share Page"
    When I enter the following data into corresponding input fields on "Second Value Of Unquoted Share Page"
      | value | 5000 |
    And I click save and continue button on "Second Value Of Unquoted Share Page"
    Then I am presented with the "Second Number Of Unquoted Share Page"
    And I should see the heading "How many unquoted shares in this company are part of this transfer?"
    When I enter the following data into corresponding input fields on "Number Of Unquoted Share Page"
      | value | 1000 |
    And I click save and continue button on "Second Number Of Unquoted Share Page"
    Then I am presented with the "Second Class Of Unquoted Share Page"
    And I should see the heading "What class are these unquoted shares?"
    When I enter the following data into corresponding input fields on "Class Of Unquoted Share Page"
      | value | Class B|
    And I click save and continue button on "Second Class Of Unquoted Share Page"
    Then I am presented with the "Second Unquoted Share Check Your Answers Page"
    And I should see the heading "Check your answers"
    And I click save and continue button on "Second Unquoted Share Check Your Answers Page"
    Then I am presented with the "Unquoted Share Amend Continue Page"
    And I should see the heading "You have added 2 groups of unquoted shares"
    And I should see two radio buttons: "Yes" and "No"
    When I select radio button "No" on "Unquoted Share Amend Continue Page"
    And I click save and continue button on "Unquoted Share Amend Continue Page"
    Then I am presented with the "Check Your Answers Page"
    And I should see the heading "Check your answers"
    And I click save and continue button on "Check Your Answers Page"

  Scenario:3 . PSA/PSP user is able to remove the Unquoted Shares from the added list
    And I "select" checkbox "Unquoted shares" on "Type Of Asset Page"
    And I click save and continue button on "Type Of Asset Page"
    Then I am presented with the "Add UnQuoted Share Start Page"
    And I should see the following values on the page
      | The following questions are about Unquoted shares that is part of this transfer. |
    And I click save and continue button on "Add UnQuoted Share Start Page"
    Then I am presented with the "Name Of Company Unquoted Share Page"
    And I should see the heading "What is the name of the company these unquoted shares relate to?"
    When I enter the following data into corresponding input fields on "Name Of Company Unquoted Share Page"
      | value | Company XYZ|
    And I click save and continue button on "Name Of Company Unquoted Share Page"
    Then I am presented with the "Value Of Unquoted Share Page"
    When I enter the following data into corresponding input fields on "Value Of Unquoted Share Page"
      | value | 500 |
    And I click save and continue button on "Value Of Unquoted Share Page"
    Then I am presented with the "Number Of Unquoted Share Page"
    And I should see the heading "How many unquoted shares in this company are part of this transfer?"
    When I enter the following data into corresponding input fields on "Number Of Unquoted Share Page"
      | value | 100 |
    And I click save and continue button on "Number Of Unquoted Share Page"
    Then I am presented with the "Class Of Unquoted Share Page"
    And I should see the heading "What class are these unquoted shares?"
    When I enter the following data into corresponding input fields on "Class Of Unquoted Share Page"
      | value | Class A|
    And I click save and continue button on "Class Of Unquoted Share Page"
    Then I am presented with the "Unquoted Share Check Your Answers Page"
    And I should see the heading "Check your answers"
    And I click save and continue button on "Unquoted Share Check Your Answers Page"
    Then I am presented with the "Unquoted Share Amend Continue Page"
    And I should see the heading "You have added 1 group of unquoted shares"
    When I select radio button "Yes" on "Unquoted Share Amend Continue Page"
    And I click save and continue button on "Unquoted Share Amend Continue Page"
    Then I am presented with the " Second Name Of Company Unquoted Share Page"
    And I should see the heading "What is the name of the company these unquoted shares relate to?"
    When I enter the following data into corresponding input fields on "Name Of Company Unquoted Share Page"
      | value | Company ABC|
    And I click save and continue button on "Second Name Of Company Unquoted Share Page"
    Then I am presented with the "Second Value Of Unquoted Share Page"
    When I enter the following data into corresponding input fields on "Second Value Of Unquoted Share Page"
      | value | 5000 |
    And I click save and continue button on "Second Value Of Unquoted Share Page"
    Then I am presented with the "Second Number Of Unquoted Share Page"
    And I should see the heading "How many unquoted shares in this company are part of this transfer?"
    When I enter the following data into corresponding input fields on "Number Of Unquoted Share Page"
      | value | 1000 |
    And I click save and continue button on "Second Number Of Unquoted Share Page"
    Then I am presented with the "Second Class Of Unquoted Share Page"
    And I should see the heading "What class are these unquoted shares?"
    When I enter the following data into corresponding input fields on "Class Of Unquoted Share Page"
      | value | Class B|
    And I click save and continue button on "Second Class Of Unquoted Share Page"
    Then I am presented with the "Second Unquoted Share Check Your Answers Page"
    And I should see the heading "Check your answers"
    And I click save and continue button on "Second Unquoted Share Check Your Answers Page"
    Then I am presented with the "Unquoted Share Amend Continue Page"
    And I should see the heading "You have added 2 groups of unquoted shares"
    And I should see two radio buttons: "Yes" and "No"
    When I click on "unquoted-shares-confirm-removal" button on "Unquoted Share Amend Continue Page"
    Then I am presented with the "Unquoted Share Confirm Removal Page"
    And I should see two radio buttons: "Yes" and "No"
    When I select radio button "Yes" on "Unquoted Share Confirm Removal Page"
    And I click save and continue button on "Unquoted Share Confirm Removal Page"
    Then I am presented with the "Unquoted Share Amend Continue Page"
    And I should see the heading "You have added 1 group of unquoted shares"
    When I select radio button "No" on "Unquoted Share Amend Continue Page"
    And I click save and continue button on "Unquoted Share Amend Continue Page"
    Then I am presented with the "Check Your Answers Page"
    And I click save and continue button on "Check Your Answers Page"

  Scenario:4 . PSA/PSP user is able to add another Unquoted Share when they go from the CYA page
    And I "select" checkbox "Unquoted shares" on "Type Of Asset Page"
    And I click save and continue button on "Type Of Asset Page"
    Then I am presented with the "Add UnQuoted Share Start Page"
    And I should see the following values on the page
      | The following questions are about unquoted shares that is part of this transfer. |
    And I click save and continue button on "Add UnQuoted Share Start Page"
    Then I am presented with the "Name Of Company Unquoted Share Page"
    And I should see the heading "What is the name of the company these unquoted shares relate to?"
    When I enter the following data into corresponding input fields on "Name Of Company Unquoted Share Page"
      | value | Company XYZ|
    And I click save and continue button on "Name Of Company Unquoted Share Page"
    Then I am presented with the "Value Of Unquoted Share Page"
    When I enter the following data into corresponding input fields on "Value Of Unquoted Share Page"
      | value | 500 |
    And I click save and continue button on "Value Of Unquoted Share Page"
    Then I am presented with the "Number Of Unquoted Share Page"
    And I should see the heading "How many unquoted shares in this company are part of this transfer?"
    When I enter the following data into corresponding input fields on "Number Of Unquoted Share Page"
      | value | 100 |
    And I click save and continue button on "Number Of Unquoted Share Page"
    Then I am presented with the "Class Of Unquoted Share Page"
    And I should see the heading "What class are these unquoted shares?"
    When I enter the following data into corresponding input fields on "Class Of Unquoted Share Page"
      | value | Class A|
    And I click save and continue button on "Class Of Unquoted Share Page"
    Then I am presented with the "Unquoted Share Check Your Answers Page"
    And I should see the heading "Check your answers"
    And I click save and continue button on "Unquoted Share Check Your Answers Page"
    Then I am presented with the "Unquoted Share Amend Continue Page"
    And I should see the heading "You have added 1 group of unquoted shares"
    And I should see two radio buttons: "Yes" and "No"
    When I select radio button "No" on "Unquoted Share Amend Continue Page"
    And I click save and continue button on "Unquoted Share Amend Continue Page"
    Then I am presented with the "Check Your Answers Page"
    When I click on "change-unquoted-shares-amend" button on "Check Your Answers Page"
    Then I am presented with the "Change Unquoted Share Amend Continue Page"
    And I should see two radio buttons: "Yes" and "No"
    When I select radio button "Yes" on "Change Unquoted Share Amend Continue Page"
    And I click save and continue button on "Change Unquoted Share Amend Continue Page"
    Then I am presented with the "Second Name Of Company Unquoted Share Page"
    And I should see the heading "What is the name of the company these unquoted shares relate to?"
    When I enter the following data into corresponding input fields on "Name Of Company Unquoted Share Page"
      | value | Company ABC|
    And I click save and continue button on "Second Name Of Company Unquoted Share Page"
    Then I am presented with the "Second Value Of Unquoted Share Page"
    When I enter the following data into corresponding input fields on "Second Value Of Unquoted Share Page"
      | value | 5000 |
    And I click save and continue button on "Second Value Of Unquoted Share Page"
    Then I am presented with the "Second Number Of Unquoted Share Page"
    And I should see the heading "How many unquoted shares in this company are part of this transfer?"
    When I enter the following data into corresponding input fields on "Number Of Unquoted Share Page"
      | value | 1000 |
    And I click save and continue button on "Second Number Of Unquoted Share Page"
    Then I am presented with the "Second Class Of Unquoted Share Page"
    And I should see the heading "What class are these unquoted shares?"
    When I enter the following data into corresponding input fields on "Class Of Unquoted Share Page"
      | value | Class B|
    And I click save and continue button on "Second Class Of Unquoted Share Page"
    Then I am presented with the "Second Unquoted Share Check Your Answers Page"
    And I should see the heading "Check your answers"
    And I click save and continue button on "Second Unquoted Share Check Your Answers Page"
    Then I am presented with the "Unquoted Share Amend Continue Page"
    And I should see the heading "You have added 2 groups of unquoted shares"
    When I select radio button "No" on "Unquoted Share Amend Continue Page"
    And I click save and continue button on "Unquoted Share Amend Continue Page"
    Then I am presented with the "Check Your Answers Page"
    And I click save and continue button on "Check Your Answers Page"